<?php

namespace App\Http\Controllers\Api;

use App\Country;
use App\CustomObjects\CustomJsonResponse;
use App\Friends;
use App\Http\Controllers\Controller;
use App\Keyword;
use App\KeywordsCache;
use App\Page;
use App\Privacy;
use App\Service\CacheService;
use App\Service\IpService;
use App\User;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;

class InitController extends Controller
{

    /**
     * @return array
     */
    public function init(Request $request, CacheService $cache)
    {
        // Log::info('INIT reqest latest',[$request]);
        $IP = $request->server->get('REMOTE_ADDR');

        $IPService = $cache->cache->get($IP);

        if (is_null($IPService) || !$IPService) {
            $IPService = (new IpService())->getCountryData($IP);
            $cache->cache->set($IP, serialize($IPService));
        }
        $IPService = (new IpService())->getCountryData($IP);
        
        $init = [
            'ipService' => $IPService,
            'user' => User::with(['userDetails', 'friends.friend.userDetails', 'pendingFriends', 'pendingFriends.user.userDetails', 'country', 'pendingRequestFriends', 'city'])->find(Auth::id())
        ];

        $customResponse = new CustomJsonResponse(
            200,
            'msg.info.init.success',
            $init
        );
        // Log::info('INIT ',[$init]);
        return $customResponse->getResponse();
    }


    /**
     * @return array
     */
    public function panelInit()
    {
        $auth = Auth::user();
        $country = Country::find($auth->country_id);
        $friend = Friends::with(['friend.userDetails'])->where('user', '=', $auth->id)->get();

        $init = ['country' => $country, 'role' => $auth->roles[0]];
        $customResponse = new CustomJsonResponse(
            200,

            'msg.info.login.success',
            $init
        );

        return $customResponse->getResponse();
    }

    // public function i18n() 
    // {

    //     $keyword = KeywordsCache::orderBy('id', 'desc')->first();

    //     if ($keyword == null) {

    //         (new CacheService())->keywordCacheCreate();
    //         $keyword = KeywordsCache::orderBy('id', 'desc')->first();
    //     }

    //     $decodedBody = json_decode((string) $keyword->body, null, 512, JSON_THROW_ON_ERROR);
    //     if (isset($decodedBody['null'])) { //added this block for world page translation with country code null
    //     // Log::info('inside if HELLO------');
    //     $decodedBody['en'] = $decodedBody['null'];
    //    }
    //     // Log the decoded body
    //     // Log::info('i18n response body:', ['body' => $decodedBody]);
    //     return response()->json($decodedBody);
    //     // return response()->json(json_decode((string) $keyword->body, null, 512, JSON_THROW_ON_ERROR));
    // }

    public function i18n()
{
    $keyword = KeywordsCache::orderBy('id', 'desc')->first();

    if ($keyword == null) {
        (new CacheService())->keywordCacheCreate();
        $keyword = KeywordsCache::orderBy('id', 'desc')->first();
    }

    // Decode as associative array
    $decodedBody = json_decode((string) $keyword->body, true, 512, JSON_THROW_ON_ERROR);

    // ✅ Case 1: If 'en' is missing but 'us' is available, copy it
    if (!isset($decodedBody['en']) && isset($decodedBody['us'])) {
        $decodedBody['en'] = $decodedBody['us'];
    }

    // ✅ Case 2: If both 'en' and 'us' are missing, insert fallback English manually
    if (!isset($decodedBody['en'])) {
        $decodedBody['en'] = [      
                    "msg.success_survey_add"=> "Survey request has been sent to administrator.",
                    "msg.required_phone_number"=>"You must confirm sms code",
                    "msg.error_exceed_max_character"=>"Max character exceeded.",
                     "lbl.delete_account_text"=>"Please click the link if you want to delete your account.",
                     "msg.success_category_create"=>"Sub-category has been created and pending for approval.",
                     "msg.error_unauthorized_country"=>"You are not authorized in this country",
                     "msg.success_register"=>"Your account has been created.",
                     "msg.error_verify_incorrect"=>"Verification code is incorrect.",
                     "msg.error_verify_sms"=>"Verification SMS could not be sent.",
                     "msg.required_confirm_password"=>"Please re-type password.",
                     "msg.required_password"=>"Password is required.",
                     "msg.required_email"=>"E-mail is required",
                     "msg.required_lastname"=>"Surname is required.",
                     "msg.required_firstname"=>"First name is required.",
                     "msg.success_login"=>"Login successful",
                     "msg.success_choice_add"=>"New candidate has been created and waiting for approval.",
                     "msg.error_unauthorized_choice"=>"You are not allowed to add candidate in another country.",
                     "msg.success_mark"=>"Rating has been registered.",
                     "msg.error_unauthorized_mark"=>"-",
                     "msg.required_old_password"=>"Old password is required.",
                     "msg.error_password_not_match"=>"Passwords do not match.",
                     "msg.success_delete_account"=>"Confirmation email has been sent to your current e-mail address",
                     "msg.error_friend_request_cancel"=>"Request could not be cancelled.",
                     "msg.success_friend_request_cancel"=>"Request has been cancelled.",
                     "msg.error_friend_respond"=>"Request could not be responded.",
                     "msg.friend_request_yes"=>"Person has been added to friend list.",
                     "msg.friend_request_no"=>"Friendship request has been declined.",
                     "msg.success_friend_remove"=>"Person has been removed from friend list.",
                     "msg.error_friend_remove"=>"Person could not be removed from friend list.",
                     "msg.required_choice_title"=>"Title is required.",
                     "msg.required_description"=>"Description is required.",
                     "msg.error_survey_add"=>"Survey could not be created.",
                     "msg.required_title"=>"Title is required.",
                     "msg.error_profile_update"=>"Profile could not be updated.",
                     "msg.error_marking"=>"Your are not authorized in this country",
                     "msg.error_email_change"=>"This email has already been registered in our system.",
                     "msg.error_enter_password"=>"Please enter password.",
                     "msg.success_profile_update"=>"Profile has been updated.",
                     "msg.success_vote"=>"Voted successfully.",
                     "msg.success_comment_save"=>"Your comment has been saved.",
                     "msg.error_comment_save"=>"Your are not allowed to comment in another country",
                     "msg.updated"=>"Updated",
                     "msg.error_login_invalid"=>"E-mail or password is incorrect.",
                     "msg.success_email_change"=>"Confirmation email has been sent to your current e-mail address.",
                     "msg.error_select_category"=>"Please select a category.",
                     "msg.error_select_parent"=>"Please select a parent category.",
                     "msg.error_enter_name"=>"Please enter a name.",
                     "msg.error_login"=>"Login failed",
                     "msg.success_comment_delete"=>"Comment has been deleted.",
                     "msg.error_comment_delete"=>"Comment could not be deleted.",
                     "msg.success_comment_like"=>"You liked this comment",
                     "msg.error_profile_delete"=>"Profile could not be deleted.",
                     "msg.success_password_change"=>"Password has been updated.",
                     "msg.error_old_password"=>"Password is wrong.",
                     "msg.error_password_change"=>"Password could not be changed.",
                     "msg.success_profile_delete"=>"Profile has been deleted.",
                     "msg.error_password_reset"=>"Password reset e-mail could not be sent.",
                     "msg.error_register"=>"Sign up failed. This number or e-mail address is already registered.",
                     "msg.success_verify_sms"=>"Verification SMS has been sent.",
                     "msg.success_password_reset"=>"New password confirmation link is sent to your e-mail address.",
                     "msg.error_answer"=>"Friend request could not be answered.",
                     "msg.error_friend_request"=>"Friendship request could not be sent.",
                     "msg.success_friend_request"=>"Friendship request has been sent.",
                     "msg.error_category_create"=>"Category could not be created.",
                     "lbl.newest"=>"Newest surveys",
                     "lbl.show_more"=>"Show more",
                     "lbl.cancel_vote"=>"Warning",
                     "lbl.okay"=>"Submit",
                     "lbl.subjects"=>"By subjects",
                     "lbl.add_new_survey"=>"Do you want to add a survey?",
                     "lbl.new_choice"=>"Add new candidate",
                     "lbl.cancel"=>"Cancel",
                     "lbl.terms_of_use"=>"Terms of use",
                     "lbl.terms_of_use_text"=>"Your request will be published after confirmation of administrator.",
                     "lbl.approve"=>"Approve",
                     "lbl.sort_score"=>"By score",
                     "lbl.sort_alphabetic"=>"Alphabetic order",
                     "lbl.comments"=>"Comments",
                     "lbl.write_comment"=>"Write a comment",
                     "lbl.answer"=>"Reply",
                     "lbl.show_comments"=>"Show comments",
                     "lbl.hide_comments"=>"Hide comments",
                     "lbl.save"=>"Save",
                     "lbl.edit"=>"Edit",
                     "lbl.delete"=>"Delete",
                     "lbl.top_voted"=>"Most voted surveys",
                     "lbl.add_new_option"=>"Add new candidate",
                     "lbl.rate"=>"Rate",
                     "lbl.name"=>"Name",
                     "lbl.description"=>"Description",
                     "lbl.add_image"=>"Add picture",
                     "lbl.email"=>"E-mail address",
                     "lbl.password"=>"Password",
                     "lbl.login"=>"Login",
                     "lbl.register"=>"Register",
                     "lbl.verify_profile"=>"Verify your profile",
                     "lbl.complete_profile"=>"Please complete all required informations in your profile.",
                     "lbl.firstname"=>"First name",
                     "lbl.middle_name"=>"Middle name",
                     "lbl.lastname"=>"Surname",
                     "lbl.phone_number"=>"Phone number",
                     "lbl.confirm_password"=>"Confirm password",
                     "lbl.verify_code"=>"SMS verification code",
                     "lbl.verify_code_description"=>"Please enter the verification code sent to your number.",
                     "lbl.reset_password_first"=>"If you forgot your password",
                     "lbl.click_here"=>"Click here",
                     "lbl.categories"=>"Categories",
                     "lbl.new_category"=>"New sub-category",
                     "lbl.select_category"=>"Select category",
                     "lbl.subcategory_name"=>"Sub category name",
                     "lbl.add_friend"=>"Add friend",
                     "lbl.old_password"=>"Old password",
                     "lbl.who_can_see"=>"Who can see my profile?",
                     "lbl.middlename"=>"Middle name",
                     "lbl.birthdate"=>"Birth date",
                     "lbl.gender"=>"Gender",
                     "lbl.education"=>"Education",
                     "lbl.country"=>"Country",
                     "lbl.friends"=>"Friends",
                     "lbl.username"=>"Username",
                     "lbl.change"=>"Change",
                     "lbl.activate_account"=>"Please confirm your identity to activate your account.",
                     "lbl.valid_identity"=>"Valid Identity (should be clear and readable)",
                     "lbl.recent_picture"=>"Recent picture (will be compared to ID picture)",
                     "lbl.delete_account"=>"Delete Account",
                     "lbl.reset_password"=>"Reset your password",
                     "lbl.enter_email"=>"Enter your e-mail",
                     "lbl.new_password"=>"New password",
                     "lbl.settings"=>"Settings",
                     "lbl.logout"=>"Logout",
                     "lbl.privacy"=>"Privacy",
                     "lbl.my_profile"=>"My profile1",
                     "lbl.survey_title"=>"Survey title",
                     "lbl.add_survey"=>"Add Survey",
                     "lbl.vote"=>"Vote",
                     "lbl.survey_already_voted"=>"You have already voted for this survey. Do you want to cancel previous vote?",
                     "lbl.mail_title_delete_profile"=>"Delete Profile",
                     "lbl.mail_title_reset_password"=>"Reset Password",
                     "lbl.mail_title_change_email"=>"Change Email",
                     "lbl.choice_already_voted"=>"You have already voted for this candidate. Would you like to cancel your previous vote?",
                     "lbl.like"=>"Like",
                     "lbl.change_email"=>"Change my email",
                     "lbl.change_email_title"=>"Are you sure you want to change your email?",
                     "lbl.sure_change_email"=>"Are you sure you want to change your email address to entered one?",
                     "lbl.sure_delete_comment"=>"Are you sure you want to delete the comment?",
                     "lbl.no_comments"=>"There are no comments yet.",
                     "lbl.no_requests"=>"There is not any notification",
                     "lbl.choices"=>"Candidates",
                     "lbl.share"=>"Share",
                     "lbl.accept"=>"Accept",
                     "lbl.refuse"=>"Refuse",
                     "lbl.about"=>"About me",
                     "lbl.no_survey"=>"There are no surveys in this category.",
                     "lbl.no_answer"=>"This survey does not have active choices.",
                     "lbl.cancel_request"=>"Cancel request",
                     "lbl.remove_friend"=>"Remove friend",
                     "lbl.male"=>"Male",
                     "lbl.female"=>"Female",
                     "lbl.gender_other"=>"No response",
                     "lbl.university"=>"University",
                     "lbl.high_school"=>"High school",
                     "lbl.school"=>"Primary school",
                     "lbl.city"=>"City",
                     "lbl.occupation"=>"Occupation",
                     "lbl.marital_status"=>"Marital status",
                     "lbl.single"=>"Single",
                     "lbl.married"=>"Married",
                     "lbl.divorced"=>"Divorced",
                     "lbl.facebook_url"=>"Facebook",
                     "lbl.instagram_url"=>"Instagram",
                     "lbl.twitter_url"=>"Twitter",
                     "lbl.skype_url"=>"Skype",
                     "lbl.web_url"=>"Website",
                     "lbl.another_url"=>"Other",
                     "lbl.everyone"=>"Everyone",
                     "lbl.friend"=>"Friends",
                     "lbl.nobody"=>"Nobody",
                     "lbl.go"=>"Go",
                     "lbl.mail_click_here"=>"Click here",
                     "lbl.write_comment_placeholder"=>"Your comment",
                     "msg.success_marking"=>"Your vote has been registered.",
                     "lbl.no_top_voted"=>"No survey",
                     "lbl.no_newest"=>"No new survey",
                     "msg.success_email_changed"=>"Your e-mail address has been changed.",
                     "msg.error_email_changed"=>"Your e-mail address could not be changed.",
                     "lbl.year"=>"Year",
                     "lbl.month"=>"Month",
                     "lbl.day"=>"Day",
                     "lbl.january"=>"January",
                     "lbl.february"=>"February",
                     "lbl.march"=>"March",
                     "lbl.april"=>"April",
                     "lbl.may"=>"May",
                     "lbl.june"=>"June",
                     "lbl.july"=>"July",
                     "lbl.august"=>"August",
                     "lbl.september"=>"September",
                     "lbl.october"=>"October",
                     "lbl.november"=>"November",
                     "lbl.december"=>"December",
                     "category.miscellaneous"=>"MISCELLANEOUS",
                     "msg.must_approved"=>"In order to vote, you must complete your profile info",
                     "lbl.resend"=>"Send new code",
                     "msg.not_allowed"=>"Action restricted for this country",
                     "msg.error_choice_add"=>"Error: New candidate has not been created",
                     "msg.error_mark"=>"-",
                     "lbl.show_less"=>"Show less",
                     "lbl.no_subject"=>"No subjects available",
                     "msg.error_email_already_used"=>"Sign up failed. This e-mail address is already registered.",
                     "msg.error_phone_number_already_used"=>"Sign up failed. This number is already registered.",
                     "subject.politics"=>"Politics",
                     "subject.economy"=>"Economy",
                     "subject.law"=>"Law",
                     "subject.sport"=>"Sport",
                     "subject.music"=>"Music",
                     "subject.news"=>"News",
                     "subject.tourism"=>"Tourism",
                     "choices.0.choice_image"=>"Image is required",
                     "choices.1.choice_image"=>"Image is required",
                     "choices.2.choice_image"=>"Image is required",
                     "'choices.4.choice_image'"=>"Image  is required",
                     "msg.candidate_image_required"=>"Candidate image is required",
                     "msg.info.like.created"=>"Comment has been liked.",
                     "msg.info.like.deleted"=>"Comment has been disliked.",
                     "msg.rating_required"=>"Rating is required",
                     "msg.success_comment_dislike"=>"You disliked this comment",
                     "subject.health"=>"Health",
                     "subject.brands"=>"Brands",
                     "msg.display"=>"Display pie graph",
                     "msg.modal_title"=>"Special survey",
                     "msg.success_verify_otp"=>"Verified OTP successfully.",
                     "lbl.register_with_google"=>"Register with Google",
                     "msg.error_delete_account"=>"Unable to delete account , something went wrong",
                     "mobile_verification_warning"=>"Please verify the mobile number",
                     "msg.error_country_vote_notallowed"=>"You are not authorized with this country",
                     "category.test-music"=>"test music",
                     "category.music"=>"Music",
                     "msg.error.account_not_approved"=>"Please verify your account.",
                     "msg.login_message"=>"Now you can login to your account.",
                     "page-about"=>"About",
                     "page-faq"=>"FAQ",
                     "page-terms-of-use"=>"Terms of Use",
                     "page-contact"=>"Contact",
                     "page-privacy-policy"=>"Privacy policy",
                     "msg.success_survey_add"=>"Survey request has been sent to administrator.",
                     "msg.required_phone_number"=>"You must confirm sms code",
                     "msg.error_exceed_max_character"=>"Max character exceeded.",
                     "lbl.delete_account_text"=>"Please click the link if you want to delete your account.",
                     "msg.success_category_create"=>"Sub-category has been created and pending for approval.",
                     "msg.error_unauthorized_country"=>"You are not authorized in this country",
                     "msg.success_register"=>"Your account has been created.",
                     "msg.error_verify_incorrect"=>"Verification code is incorrect.",
                     "msg.error_verify_sms"=>"Verification SMS could not be sent.",
                     "msg.required_confirm_password"=>"Please re-type password.",
                     "msg.required_password"=>"Password is required.",
                     "msg.required_email"=>"E-mail is required",
                     "msg.required_lastname"=>"Surname is required.",
                     "msg.required_firstname"=>"First name is required.",
                     "msg.success_login"=>"Login successful",
                     "msg.success_choice_add"=>"New candidate has been created and waiting for approval.",
                     "msg.error_unauthorized_choice"=>"You are not allowed to add candidate in another country.",
                     "msg.success_mark"=>"Rating has been registered.",
                     "msg.error_unauthorized_mark"=>"-",
                     "msg.required_old_password"=>"Old password is required.",
                     "msg.error_password_not_match"=>"Passwords do not match.",
                     "msg.success_delete_account"=>"Confirmation email has been sent to your current e-mail address",
                     "msg.error_friend_request_cancel"=>"Request could not be cancelled.",
                     "msg.success_friend_request_cancel"=>"Request has been cancelled.",
                     "msg.error_friend_respond"=>"Request could not be responded.",
                     "msg.friend_request_yes"=>"Person has been added to friend list.",
                     "msg.friend_request_no"=>"Friendship request has been declined.",
                     "msg.success_friend_remove"=>"Person has been removed from friend list.",
                     "msg.error_friend_remove"=>"Person could not be removed from friend list.",
                     "msg.required_choice_title"=>"Title is required.",
                     "msg.required_description"=>"Description is required.",
                     "msg.error_survey_add"=>"Survey could not be created.",
                     "msg.required_title"=>"Title is required.",
                     "msg.error_profile_update"=>"Profile could not be updated.",
                     "msg.error_marking"=>"Your are not authorized in this country",
                     "msg.error_email_change"=>"This email has already been registered in our system.",
                     "msg.error_enter_password"=>"Please enter password.",
                     "msg.success_profile_update"=>"Profile has been updated.",
                     "msg.success_vote"=>"Voted successfully.",
                     "msg.success_comment_save"=>"Your comment has been saved.",
                     "msg.error_comment_save"=>"Your are not allowed to comment in another country",
                     "msg.updated"=>"Updated",
                     "msg.error_login_invalid"=>"E-mail or password is incorrect.",
                     "msg.success_email_change"=>"Confirmation email has been sent to your current e-mail address.",
                     "msg.error_select_category"=>"Please select a category.",
                     "msg.error_select_parent"=>"Please select a parent category.",
                     "msg.error_enter_name"=>"Please enter a name.",
                     "msg.error_login"=>"Login failed",
                     "msg.success_comment_delete"=>"Comment has been deleted.",
                     "msg.error_comment_delete"=>"Comment could not be deleted.",
                     "msg.success_comment_like"=>"You liked this comment",
                     "msg.error_profile_delete"=>"Profile could not be deleted.",
                     "msg.success_password_change"=>"Password has been updated.",
                     "msg.error_old_password"=>"Password is wrong.",
                     "msg.error_password_change"=>"Password could not be changed.",
                     "msg.success_profile_delete"=>"Profile has been deleted.",
                     "msg.error_password_reset"=>"Password reset e-mail could not be sent.",
                     "msg.error_register"=>"Sign up failed. This number or e-mail address is already registered.",
                     "msg.success_verify_sms"=>"Verification SMS has been sent.",
                     "msg.success_password_reset"=>"New password confirmation link is sent to your e-mail address.",
                     "msg.error_answer"=>"Friend request could not be answered.",
                     "msg.error_friend_request"=>"Friendship request could not be sent.",
                     "msg.success_friend_request"=>"Friendship request has been sent.",
                     "msg.error_category_create"=>"Category could not be created.",
                     "lbl.newest"=>"Newest surveys",
                     "lbl.show_more"=>"Show more",
                     "lbl.cancel_vote"=>"Warning",
                     "lbl.okay"=>"Submit",
                     "lbl.subjects"=>"By subjects",
                     "lbl.add_new_survey"=>"Do you want to add a survey?",
                     "lbl.new_choice"=>"Add new candidate",
                     "lbl.cancel"=>"Cancel",
                     "lbl.terms_of_use"=>"Terms of use",
                     "lbl.terms_of_use_text"=>"Your request will be published after confirmation of administrator.",
                     "lbl.approve"=>"Approve",
                     "lbl.sort_score"=>"By score",
                     "lbl.sort_alphabetic"=>"Alphabetic order",
                     "lbl.comments"=>"Comments",
                     "lbl.write_comment"=>"Write a comment",
                     "lbl.answer"=>"Reply",
                     "lbl.show_comments"=>"Show comments",
                     "lbl.hide_comments"=>"Hide comments",
                     "lbl.save"=>"Save",
                     "lbl.edit"=>"Edit",
                     "lbl.delete"=>"Delete",
                     "lbl.top_voted"=>"Most voted surveys",
                     "lbl.add_new_option"=>"Add new candidate",
                     "lbl.rate"=>"Rate",
                     "lbl.name"=>"Name",
                     "lbl.description"=>"Description",
                     "lbl.add_image"=>"Add picture",
                     "lbl.world"=>"World",
                     "lbl.email"=>"E-mail address",
                     "lbl.password"=>"Password",
                     "lbl.login"=>"Login",
                     "lbl.register"=>"Register",
                     "lbl.verify_profile"=>"Verify your profile",
                     "lbl.complete_profile"=>"Please complete all required informations in your profile.",
                     "lbl.firstname"=>"First name",
                     "lbl.middle_name"=>"Middle name",
                     "lbl.lastname"=>"Surname",
                     "lbl.phone_number"=>"Phone number",
                     "lbl.confirm_password"=>"Confirm password",
                     "lbl.verify_code"=>"SMS verification code",
                     "lbl.verify_code_description"=>"Please enter the verification code sent to your number.",
                     "lbl.reset_password_first"=>"If you forgot your password",
                     "lbl.click_here"=>"Click here",
                     "lbl.categories"=>"Categories",
                     "lbl.new_category"=>"New sub-category",
                     "lbl.select_category"=>"Select category",
                     "lbl.subcategory_name"=>"Sub category name",
                     "lbl.add_friend"=>"Add friend",
                     "lbl.old_password"=>"Old password",
                     "lbl.who_can_see"=>"Who can see my profile?",
                     "lbl.middlename"=>"Middle name",
                     "lbl.birthdate"=>"Birth date",
                     "lbl.gender"=>"Gender",
                     "lbl.education"=>"Education",
                     "lbl.country"=>"Country",
                     "lbl.friends"=>"Friends",
                     "lbl.username"=>"Username",
                     "lbl.change"=>"Change",
                     "lbl.activate_account"=>"Please confirm your identity to activate your account.",
                     "lbl.valid_identity"=>"Valid Identity (should be clear and readable)",
                     "lbl.recent_picture"=>"Recent picture (will be compared to ID picture)",
                     "lbl.delete_account"=>"Delete Account",
                     "lbl.reset_password"=>"Reset your password",
                     "lbl.enter_email"=>"Enter your e-mail",
                     "lbl.new_password"=>"New password",
                     "lbl.settings"=>"Settings",
                     "lbl.logout"=>"Logout",
                     "lbl.privacy"=>"Privacy",
                     "lbl.my_profile"=>"My profile1",
                     "lbl.survey_title"=>"Survey title",
                     "lbl.add_survey"=>"Add Survey",
                     "lbl.vote"=>"Vote",
                     "lbl.survey_already_voted"=>"You have already voted for this survey. Do you want to cancel previous vote?",
                     "lbl.mail_title_delete_profile"=>"Delete Profile",
                     "lbl.mail_title_reset_password"=>"Reset Password",
                     "lbl.mail_title_change_email"=>"Change Email",
                     "lbl.choice_already_voted"=>"You have already voted for this candidate. Would you like to cancel your previous vote?",
                     "lbl.like"=>"Like",
                     "lbl.change_email"=>"Change my email",
                     "lbl.change_email_title"=>"Are you sure you want to change your email?",
                     "lbl.sure_change_email"=>"Are you sure you want to change your email address to entered one?",
                     "lbl.sure_delete_comment"=>"Are you sure you want to delete the comment?",
                     "lbl.no_comments"=>"There are no comments yet.",
                     "lbl.no_requests"=>"There is not any notification",
                     "lbl.choices"=>"Candidates",
                     "lbl.share"=>"Share",
                     "lbl.accept"=>"Accept",
                     "lbl.refuse"=>"Refuse",
                     "lbl.about"=>"About me",
                     "lbl.no_survey"=>"There are no surveys in this category.",
                     "lbl.no_answer"=>"This survey does not have active choices.",
                     "lbl.cancel_request"=>"Cancel request",
                     "lbl.remove_friend"=>"Remove friend",
                     "lbl.male"=>"Male",
                     "lbl.female"=>"Female",
                     "lbl.gender_other"=>"No response",
                     "lbl.university"=>"University",
                     "lbl.high_school"=>"High school",
                     "lbl.school"=>"Primary school",
                     "lbl.city"=>"City",
                     "lbl.occupation"=>"Occupation",
                     "lbl.marital_status"=>"Marital status",
                     "lbl.single"=>"Single",
                     "lbl.married"=>"Married",
                     "lbl.divorced"=>"Divorced",
                     "lbl.facebook_url"=>"Facebook",
                     "lbl.instagram_url"=>"Instagram",
                     "lbl.twitter_url"=>"Twitter",
                     "lbl.skype_url"=>"Skype",
                     "lbl.web_url"=>"Website",
                     "lbl.another_url"=>"Other",
                     "lbl.everyone"=>"Everyone",
                     "lbl.friend"=>"Friends",
                     "lbl.nobody"=>"Nobody",
                     "lbl.go"=>"Go",
                     "lbl.mail_click_here"=>"Click here",
                     "lbl.write_comment_placeholder"=>"Your comment",
                     "msg.success_marking"=>"Your vote has been registered.",
                     "lbl.no_top_voted"=>"No survey",
                     "lbl.no_newest"=>"No new survey",
                     "msg.success_email_changed"=>"Your e-mail address has been changed.",
                     "msg.error_email_changed"=>"Your e-mail address could not be changed.",
                     "lbl.year"=>"Year",
                     "lbl.month"=>"Month",
                     "lbl.day"=>"Day",
                     "lbl.january"=>"January",
                     "lbl.february"=>"February",
                     "lbl.march"=>"March",
                     "lbl.april"=>"April",
                     "lbl.may"=>"May",
                     "lbl.june"=>"June",
                     "lbl.july"=>"July",
                     "lbl.august"=>"August",
                     "lbl.september"=>"September",
                     "lbl.october"=>"October",
                     "lbl.november"=>"November",
                     "lbl.december"=>"December",
                     "category.miscellaneous"=>"MISCELLANEOUS",
                     "msg.must_approved"=>"In order to vote, you must complete your profile info",
                     "lbl.resend"=>"Send new code",
                     "msg.not_allowed"=>"Action restricted for this country",
                     "msg.error_choice_add"=>"Error: New candidate has not been created",
                     "msg.error_mark"=>"-",
                     "lbl.show_less"=>"Show less",
                     "lbl.no_subject"=>"No subjects available",
                     "msg.error_email_already_used"=>"Sign up failed. This e-mail address is already registered.",
                     "msg.error_phone_number_already_used"=>"Sign up failed. This number is already registered.",
                     "subject.politics"=>"Politics",
                     "subject.economy"=>"Economy",
                     "subject.law"=>"Law",
                     "subject.sport"=>"World",
                     "subject.music"=>"Music",
                     "subject.news"=>"News",
                     "subject.tourism"=>"Tourism",
                     "choices.0.choice_image"=>"Image is required",
                     "choices.1.choice_image"=>"Image is required",
                     "choices.2.choice_image"=>"Image is required",
                     "'choices.4.choice_image'"=>"Image  is required",
                     "msg.candidate_image_required"=>"Candidate image is required",
                     "msg.info.like.created"=>"Comment has been liked.",
                     "msg.info.like.deleted"=>"Comment has been disliked.",
                     "msg.rating_required"=>"Rating is required",
                     "msg.success_comment_dislike"=>"You disliked this comment",
                     "subject.health"=>"Health",
                     "subject.brands"=>"Brands",
                     "msg.display"=>"Display pie graph",
                     "msg.modal_title"=>"Special survey",
                     "msg.success_verify_otp"=>"Verified OTP successfully.",
                     "lbl.register_with_google"=>"Register with Google",
                     "msg.error_delete_account"=>"Unable to delete account , something went wrong",
                     "mobile_verification_warning"=>"Please verify the mobile number",
                     "msg.error_country_vote_notallowed"=>"You are not authorized with this country",
                     "category.test-music"=>"test music",
                     "category.music"=>"Music",
                     "msg.error.account_not_approved"=>"Please verify your account.",
                     "msg.login_message"=>"Now you can login to your account.",
                     "page-about"=>"About",
                     "page-faq"=>"FAQ",
                     "page-terms-of-use"=>"Terms of Use",
                     "page-contact"=>"Contact",
                     "page-privacy-policy"=>"Privacy policy"
        ];
    }

    return response()->json($decodedBody);
}

}
