version = 1

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

# Optional: To exclude directories like vendor, node_modules, etc.
[exclude]
paths = [
  "vendor/",
  "node_modules/",
  "public/",
  "storage/",
  "bootstrap/cache/"
]
