version = 1

[[analyzers]]
name = "php"
enabled = true

[analyzers.meta]
runtime_version = "7.1"

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
runtime_version = "18"

# Optional: To exclude directories like vendor, node_modules, etc.
[exclude]
paths = [
  "vendor/",
  "node_modules/",
  "public/",
  "storage/",
  "bootstrap/cache/"
]
